# Autogenerated wrapper script for couchbase_lite_C_jll for x86_64-linux-gnu-cxx11
export libcblite

using Zlib_jll
using ICU_jll
JLLWrappers.@generate_wrapper_header("couchbase_lite_C")
JLLWrappers.@declare_library_product(libcblite, "libcblite.so.3")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, ICU_jll)
    JLLWrappers.@init_library_product(
        libcblite,
        "lib/libcblite.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
